### PR TITLE
Improve performance

### PR DESCRIPTION
**Pull request by wanhmr**
主要是去掉点语法，这样能减少许多 getter 方法的调用。

### CODE REVIEW

**Comment by wanhmr** [comment]
分支错了

**Comment by HarrisonXi** [comment]
looks like that `_recycledMuiIDItemsDic` is not initialized.

**Comment by wanhmr** [comment]
@HarrisonXi Thank you for pointing out the issue, I have fixed it.

**Comment by HarrisonXi** [comment]
Thanks for your commit.

**Pull request merged**
